apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websiteimage
  template:
    metadata:
      labels:
        app: websiteimage
    spec:
      containers:
      - name: websiteimage
        image: optimus9000/websiteimage
        ports:
        - containerPort: 80
